// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Linq.ComposableQuery")>]
[<assembly: AssemblyProductAttribute("FSharp.Linq.ComposableQuery")>]
[<assembly: AssemblyDescriptionAttribute("
  A Compositional, Safe Query Framework for Dynamic F# Queries
  A quotations evaluator for F# based on LINQ expression tree compilation. Some constructs are not supported and performance may be slower than F# compiled code. Fork from https://github.com/fsprojects/FSharp.Quotations.Evaluator. Repack using .NET SDK, targeting netstandard2.0, netcoreapp3.1, net472. Removed deprecated LinqToSQL 'Like' support. Original repo based on the old F# 2.0 PowerPack code. 
  ")>]
[<assembly: AssemblyFileVersionAttribute("1.0.5")>]
[<assembly: AssemblyInformationalVersionAttribute("1.0.5")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2020-11-24")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Linq.ComposableQuery"
    let [<Literal>] AssemblyProduct = "FSharp.Linq.ComposableQuery"
    let [<Literal>] AssemblyDescription = "
  A Compositional, Safe Query Framework for Dynamic F# Queries
  A quotations evaluator for F# based on LINQ expression tree compilation. Some constructs are not supported and performance may be slower than F# compiled code. Fork from https://github.com/fsprojects/FSharp.Quotations.Evaluator. Repack using .NET SDK, targeting netstandard2.0, netcoreapp3.1, net472. Removed deprecated LinqToSQL 'Like' support. Original repo based on the old F# 2.0 PowerPack code. 
  "
    let [<Literal>] AssemblyFileVersion = "1.0.5"
    let [<Literal>] AssemblyInformationalVersion = "1.0.5"
    let [<Literal>] AssemblyMetadata_BuildDate = "2020-11-24"
